window.AdminDashboard = function (user, navigateTo) {
    const render = () => `
    <header class="flex justify-between items-center mb-4 fade-in">
        <div>
            <h2 class="font-bold" style="font-size: 1.5rem;">${window.t('admin_dashboard_title')}</h2>
            <p class="text-sm text-secondary">Rudraprayag District</p>
        </div>
         <button onclick="(() => { localStorage.removeItem('user'); window.location.reload(); })();" class="btn" style="width:auto; padding:5px 10px; background:#f4f4f4;">Logout</button>
    </header>

    <div class="grid grid-cols-2 gap-4 mb-6">
        <div class="card p-4 text-center">
            <h3 class="font-bold text-2xl" id="stat-sakhis">15</h3>
            <p class="text-xs text-secondary">Active Sakhis</p>
        </div>
        <div class="card p-4 text-center">
            <h3 class="font-bold text-2xl" id="stat-entries">0</h3>
            <p class="text-xs text-secondary">Total Activities</p>
        </div>
        <div class="card p-4 text-center">
            <h3 class="font-bold text-2xl text-green-600" id="stat-approved">0</h3>
            <p class="text-xs text-secondary">Approved</p>
        </div>
        <div class="card p-4 text-center">
            <h3 class="font-bold text-2xl text-orange-500" id="stat-pending">0</h3>
            <p class="text-xs text-secondary">Pending</p>
        </div>
    </div>

    <div class="card">
        <h3 class="font-bold mb-4">Reports</h3>
        <button id="btn-mpr" class="btn btn-primary mb-2">
            📊 Generate District MPR (PDF)
        </button>
        <button class="btn" style="background:white; border:1px solid #ddd;">
             📥 Export CSV
        </button>
    </div>

    <div class="mt-6">
        <h3 class="font-bold mb-2">Recent System Activity</h3>
        <div id="admin-feed" class="text-sm text-secondary">
            Loading...
        </div>
    </div>

    <!-- MPR Preview Modal -->
    <div id="mpr-modal" class="modal-overlay">
        <div class="modal-content">
            <h3 class="font-bold text-xl mb-2 text-primary">MPR Preview</h3>
            <p class="text-sm text-secondary mb-4">Review the district summary before printing.</p>
            
            <div id="mpr-preview-data" class="preview-box">
                <!-- Data injected here -->
            </div>

            <div class="flex gap-4 mt-6">
                <button id="btn-mpr-download" class="btn btn-primary">
                    📥 Download PDF
                </button>
                <button id="btn-mpr-close" class="btn" style="background: #f1f5f9; color: #475569;">
                    Close
                </button>
            </div>
        </div>
    </div>
    `;

    setTimeout(() => {
        const modal = document.getElementById('mpr-modal');
        const previewData = document.getElementById('mpr-preview-data');
        const btnMpr = document.getElementById('btn-mpr');
        const btnMprDownload = document.getElementById('btn-mpr-download');
        const btnMprClose = document.getElementById('btn-mpr-close');

        // Calculate Stats
        window.DB.getAllEntries().then(entries => {
            const entryCount = entries.length;
            const approved = entries.filter(e => e.approvalStatus === 'approved').length;
            const pending = entryCount - approved;

            document.getElementById('stat-entries').innerText = entryCount;
            document.getElementById('stat-approved').innerText = approved;
            document.getElementById('stat-pending').innerText = pending;

            const feed = document.getElementById('admin-feed');
            feed.innerHTML = entries.slice(0, 5).map(e => `
                <div class="py-2 border-b">
                    <span class="font-bold">${e.data.activityType || 'Activity'}</span> from ${e.data.village} 
                    <span class="text-xs float-right">${new Date(e.createdAt).toLocaleDateString()}</span>
                </div>
            `).join('');

            // Open Preview Modal
            btnMpr.addEventListener('click', () => {
                const today = new Date().toLocaleDateString();
                previewData.innerHTML = `
                    <div class="preview-row"><strong>District:</strong> <span>Rudraprayag</span></div>
                    <div class="preview-row"><strong>Generated By:</strong> <span>${user.name}</span></div>
                    <div class="preview-row"><strong>Date:</strong> <span>${today}</span></div>
                    <div class="mt-3 font-bold border-b pb-1">Report Data</div>
                    <div class="preview-row"><strong>Active Sakhis:</strong> <span>15</span></div>
                    <div class="preview-row"><strong>Total Activities:</strong> <span>${entryCount}</span></div>
                    <div class="preview-row"><strong>Approved:</strong> <span>${approved}</span></div>
                    <div class="preview-row"><strong>Pending:</strong> <span>${pending}</span></div>
                `;
                modal.classList.add('active');
            });

            // Close Modal
            btnMprClose.addEventListener('click', () => {
                modal.classList.remove('active');
            });

            // Download PDF from Modal
            btnMprDownload.addEventListener('click', () => {
                console.log("AdminDashboard: MPR Generation Started from Preview");
                try {
                    const jsPDFLib = window.jspdf?.jsPDF || window.jsPDF;
                    if (!jsPDFLib) {
                        console.error("AdminDashboard: jsPDF library not found");
                        return alert("PDF Library not loaded properly.");
                    }

                    const doc = new jsPDFLib();
                    doc.setFontSize(22);
                    doc.text("District MPR - Rudraprayag", 14, 20);
                    doc.setFontSize(12);
                    doc.text(`Generated by: ${user.name}`, 14, 30);
                    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 36);

                    doc.setLineWidth(0.5);
                    doc.line(14, 40, 190, 40);

                    doc.setFontSize(14);
                    doc.text("Summary", 14, 50);
                    doc.setFontSize(11);
                    doc.text(`Total Active Sakhis: 15`, 14, 60);
                    doc.text(`Total Activities Reported: ${entryCount}`, 14, 66);
                    doc.text(`Approved by VO: ${approved}`, 14, 72);

                    doc.save("Rudraprayag_MPR.pdf");
                    modal.classList.remove('active');
                } catch (err) {
                    console.error("AdminDashboard: PDF Generation Error:", err);
                    alert("Failed to generate PDF: " + err.message);
                }
            });
        });
    }, 200);

    return render();
};


